# Generated by Django 4.2.6 on 2023-12-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='description',
        ),
        migrations.RemoveField(
            model_name='file',
            name='sections',
        ),
        migrations.DeleteModel(
            name='no_of_section',
        ),
    ]
